### Requires the VS Code REST client extension
@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@hostProtocol = http
@baseUrl={{hostProtocol}}://{{hostname}}:{{port}}/

GET {{baseUrl}}swagger-ui/index.html
