services:

  app:
    image: cestoredemo-${BUILD_BUILDNUMBER:-0.0.1}
    build: &build
      context: .
      dockerfile: ./Dockerfile

  tests:
    build:
      <<: *build
      target: test
